import type { Metadata } from "next";
import { PageHeader } from "@/components/layout/page-header";
import { Container } from "@/components/ui/section";
import { brand } from "@/config/app";
import { disclaimers } from "@/config/services";

export const metadata: Metadata = { title: "Terms" };

// Foundation text. Have it reviewed by a lawyer before launch.
export default function TermsPage() {
  return (
    <>
      <PageHeader eyebrow="Terms" title="Terms of service" />
      <Container className="prose-doc max-w-3xl">
        <h2>1. The service</h2>
        <p>{brand.name} provides (a) a free preliminary writing scan generated by this website, (b) paid AI-writing and similarity screening performed by our staff using Turnitin, and (c) paid human writing review.</p>
        <h2>2. Independence</h2>
        <p>{disclaimers.turnitin}</p>
        <h2>3. Your content</h2>
        <p>You must only submit work that you wrote yourself or are otherwise authorised to submit. You keep ownership of your work. You give us permission to store and process it only as needed to deliver the service you ordered.</p>
        <h2>4. Results</h2>
        <ul>
          <li>The free scan is a preliminary estimate of writing patterns. It is not a Turnitin result and does not determine authorship.</li>
          <li>A screening result reflects the result returned during the screening performed for your submission at that time. Results from the same document may differ at another time or in another institution&rsquo;s configuration.</li>
          <li>{disclaimers.noGuarantee} No automated indicator proves who wrote a text.</li>
        </ul>
        <h2>5. Writing review</h2>
        <p>Writing review improves clarity, flow and phrasing while preserving meaning, factual claims and citations. We will not invent sources or citations. We may decline requests that appear intended to disguise authorship.</p>
        <h2>6. Payment and refunds</h2>
        <p>Prices are shown in Hong Kong dollars before checkout. If we cannot complete a paid order, we will refund it. A new screening after revision is a new order.</p>
        <h2>7. Acceptable use</h2>
        <p>Do not use the service to misrepresent authorship, to submit others&rsquo; work without permission, or to attempt to access other users&rsquo; data.</p>
        <h2>8. Contact</h2>
        <p><a href={`mailto:${brand.supportEmail}`}>{brand.supportEmail}</a></p>
      </Container>
    </>
  );
}
