import { brand, freeScan, retention, uploads } from "./app";
import { disclaimers } from "./services";

export interface FaqItem {
  q: string;
  a: string;
}

export const faq: FaqItem[] = [
  {
    q: "What is the difference between the free scan and the screening service?",
    a: `The free scan is our own instant analysis of writing patterns such as sentence variation and repeated transitions. It is an estimate generated by this website. The screening service is a separate paid order: a person on our team runs your document through a Turnitin screening workflow and uploads the result that screening returned.`,
  },
  {
    q: "Is the free scan Turnitin?",
    a: "No. The free scan is produced entirely by this website and never touches Turnitin. It is labelled as a preliminary estimate everywhere it appears.",
  },
  {
    q: "What does the screening report include?",
    a: "Depending on what you order: the AI-writing indicator, the similarity percentage, or both, as returned by the Turnitin screening performed for your document, plus the report file where one is available. We only show values that screening actually returned. If a value was not returned (for example, when a document is too short for an AI-writing indicator), we say so rather than estimate it.",
  },
  {
    q: "Are you affiliated with Turnitin?",
    a: `No. ${disclaimers.turnitin}`,
  },
  {
    q: "Will the screening store my paper in a repository?",
    a: "No. Our processing checklist requires the screening to be run with repository storage switched off, so your paper is not added to any paper repository. This matters because a stored copy can later match your own final submission. The order cannot move to screening until that step is confirmed.",
  },
  {
    q: "Can AI-writing detectors make mistakes?",
    a: "Yes. Automated AI-writing indicators can flag genuinely human writing, particularly formal, formulaic or second-language writing. No indicator, including ours, proves who wrote a text.",
  },
  {
    q: "Can you guarantee a specific AI score?",
    a: `No. ${disclaimers.noGuarantee} A screening result reflects one run at one point in time.`,
  },
  {
    q: "What happens to my document after screening?",
    a: `Your file sits in private storage that only you and authorised staff can access, through short-lived links. Source documents are deleted ${retention.sourceDocumentDays} days after your order completes, and reports after ${retention.reportDays} days. You can ask us to delete them sooner at ${brand.supportEmail}.`,
  },
  {
    q: "How long are uploaded files stored?",
    a: `Source documents: ${retention.sourceDocumentDays} days after completion. Reports: ${retention.reportDays} days. Free-scan text is not stored by default; only the signal scores are kept so you can see your scan history.`,
  },
  {
    q: "What file types are supported?",
    a: `PDF and DOCX, up to ${Math.round(uploads.maxBytes / 1024 / 1024)} MB.`,
  },
  {
    q: "How long does screening take?",
    a: "Screening is processed by a person, so it depends on the queue. Your dashboard shows each step as it happens.",
  },
  {
    q: "What is the writing refinement service?",
    a: "A human review of your own writing for clarity, flow and natural phrasing. Your meaning, factual claims and citations are preserved, and we keep your voice. It is not a service for disguising AI-generated or third-party work.",
  },
  {
    q: "How many free scans do I get?",
    a: `${freeScan.dailyLimit} per calendar day (Hong Kong time) for every registered account. The allowance resets automatically at midnight.`,
  },
];
