import { brand, freeScan, retention } from "./app";
import { formatHKD, screeningPrices } from "./pricing";
import { enabledManualPayments } from "./payments";
import { disclaimers, refinementMinimumLabel, refinementRateLabel, reportService, wordRangeLabel } from "./services";

export interface FaqItem {
  q: string;
  a: string;
}

const payMethods = enabledManualPayments()
  .map((m) => m.label)
  .join(", ");

export const faq: FaqItem[] = [
  {
    q: "What is the difference between the free scan and the report?",
    a: `The free scan is our own instant analysis of writing patterns such as sentence variation and repeated transitions. It is an estimate generated by this website. The report is a separate paid order: you paste your text, and a person on our team runs it through a Turnitin screening workflow and records the result that screening returned.`,
  },
  {
    q: "Is the free scan Turnitin?",
    a: "No. The free scan is produced entirely by this website and never touches Turnitin. It is labelled as a preliminary estimate everywhere it appears.",
  },
  {
    q: "What does the report include?",
    a: "The AI-writing indicator and the similarity percentage, as returned by the Turnitin screening performed for your text, plus the report file where one is available. We only show values that screening actually returned. If a value was not returned (for example, when a text is too short for an AI-writing indicator), we say so rather than estimate it.",
  },
  {
    q: "How much does it cost?",
    a: `A report is ${formatHKD(screeningPrices[reportService])} for any document of ${wordRangeLabel}. Writing refinement is ${refinementRateLabel}, rounded up. ${refinementMinimumLabel}. The free scan costs nothing.`,
  },
  {
    q: "How do I submit my text?",
    a: "Press the button on the report or refinement page, paste your text into the box and press Enter. You can also load a .docx, .pdf or .txt file into the box; the text is extracted in your browser. You then choose how to pay on the order page.",
  },
  {
    q: "How do I pay?",
    a: `By ${payMethods}, with card payment where available. The order page shows the exact amount, the account details and a reference code to put in your payment note. After paying, enter your transaction number or payer name there. We confirm each payment by hand, and your order joins the queue as soon as it is confirmed. If we can't find a payment, we tell you on the order page and you can submit the details again.`,
  },
  {
    q: "Are you affiliated with Turnitin?",
    a: `No. ${disclaimers.turnitin}`,
  },
  {
    q: "Will the screening store my paper in a repository?",
    a: "No. Our processing checklist requires the screening to be run with repository storage switched off, so your paper is not added to any paper repository. This matters because a stored copy can later match your own final submission. The order cannot move to screening until that step is confirmed.",
  },
  {
    q: "Can AI-writing detectors make mistakes?",
    a: "Yes. Automated AI-writing indicators can flag genuinely human writing, particularly formal, formulaic or second-language writing. No indicator, including ours, proves who wrote a text.",
  },
  {
    q: "Can you guarantee a specific AI score?",
    a: `No. ${disclaimers.noGuarantee} A screening result reflects one run at one point in time.`,
  },
  {
    q: "What happens to my text after the report?",
    a: `Your text is kept in our database where only you and authorised staff can see it. It is deleted ${retention.sourceDocumentDays} days after your order completes, and report files after ${retention.reportDays} days. Unpaid orders are cancelled and their text deleted after ${retention.unpaidOrderDays} days. You can ask us to delete them sooner at ${brand.supportEmail}.`,
  },
  {
    q: "How long is my text stored?",
    a: `Submitted text: ${retention.sourceDocumentDays} days after the order completes (or is cancelled). Report files: ${retention.reportDays} days. Free-scan text is not stored by default; only the signal scores are kept so you can see your scan history.`,
  },
  {
    q: "How long does a report take?",
    a: "Each report is processed by a person, so it depends on the queue. Your order page shows each step as it happens and updates by itself; the result appears there as soon as it is released.",
  },
  {
    q: "What is Writing Refinement?",
    a: `A human refinement of your own writing for clarity, flow and style. Your meaning, factual claims and citations are preserved, and we keep your voice. ${disclaimers.refinement}`,
  },
  {
    q: "How many free scans do I get?",
    a: `${freeScan.dailyLimit} per calendar day (Hong Kong time). Signed-in accounts are counted per account. Visitors without an account are counted by a one-way hash of their network address, so the address itself is never stored. The allowance resets automatically at midnight.`,
  },
];
