import {
  formatHKD,
  refinementPricing,
  screeningPrices,
  type ServiceType,
} from "./pricing";
import { freeScan } from "./app";

export type ServiceKind = "free" | "screening" | "refinement";

export interface ServiceDefinition {
  id: ServiceType | "free_scan";
  kind: ServiceKind;
  name: string;
  short: string;
  priceLabel: string;
  cadence?: string;
  features: string[];
  href: string;
  cta: string;
  highlight?: boolean;
}

export const serviceLabels: Record<ServiceType, string> = {
  ai_screening: "AI-Writing Screening",
  similarity_screening: "Similarity Screening",
  combined_screening: "AI + Similarity Screening",
  refinement: "Writing Refinement",
};

export const services: ServiceDefinition[] = [
  {
    id: "free_scan",
    kind: "free",
    name: "Preliminary Scan",
    short: "Instant writing-pattern analysis generated by this website.",
    priceLabel: "HK$0",
    cadence: `${freeScan.dailyLimit} scans / day`,
    features: [
      "Instant result",
      "Six writing-pattern signals",
      "Paragraph-level indicators",
      "Not a Turnitin result",
    ],
    href: "/scan",
    cta: "Run free scan",
  },
  {
    id: "refinement",
    kind: "refinement",
    name: "Writing Review",
    short: "Human clarity and style review of your own writing.",
    priceLabel: `From ${formatHKD(refinementPricing.minimum)}`,
    cadence: `${formatHKD(refinementPricing.perBlock)} per ${refinementPricing.blockWords} words`,
    features: [
      "Human-reviewed",
      "Clarity and flow",
      "Meaning and citations preserved",
      "Your voice retained",
    ],
    href: "/services/refinement",
    cta: "Request review",
  },
  {
    id: "ai_screening",
    kind: "screening",
    name: "AI-Writing Screening",
    short: "Turnitin AI-writing indicator from a human-processed screening.",
    priceLabel: formatHKD(screeningPrices.ai_screening),
    cadence: "per document",
    features: [
      "Turnitin AI-writing indicator",
      "Report delivered to your dashboard",
      "Not stored in any repository",
    ],
    href: "/services/screening?type=ai_screening",
    cta: "Request screening",
  },
  {
    id: "similarity_screening",
    kind: "screening",
    name: "Similarity Screening",
    short: "Turnitin similarity result from a human-processed screening.",
    priceLabel: formatHKD(screeningPrices.similarity_screening),
    cadence: "per document",
    features: [
      "Turnitin similarity percentage",
      "Similarity report delivery",
      "Not stored in any repository",
    ],
    href: "/services/screening?type=similarity_screening",
    cta: "Request screening",
  },
  {
    id: "combined_screening",
    kind: "screening",
    name: "AI + Similarity",
    short: "Both indicators from one screening run.",
    priceLabel: formatHKD(screeningPrices.combined_screening),
    cadence: "per document",
    features: [
      "AI-writing indicator",
      "Similarity result",
      "Combined report delivery",
      "Not stored in any repository",
    ],
    href: "/services/screening?type=combined_screening",
    cta: "Request screening",
    highlight: true,
  },
];

export const disclaimers = {
  turnitin:
    "Turnitin is a third-party service. This platform is independently operated and is not affiliated with, endorsed by, or operated by Turnitin.",
  freeScan:
    "This preliminary assessment identifies writing patterns that may contribute to automated detector risk. It does not determine authorship and is not a Turnitin result.",
  screeningResult:
    "This report reflects the result returned during the screening performed for this submission. Automated indicators should be interpreted carefully and are not, on their own, proof of authorship.",
  noGuarantee:
    "We do not guarantee any particular AI-writing or similarity outcome.",
} as const;
