import {
  formatCredits,
  refinementPricing,
  screeningPrices,
  screeningWordRange,
  type ServiceType,
} from "./pricing";
import { freeScan } from "./app";

export type ServiceKind = "free" | "screening" | "refinement";

export interface ServiceDefinition {
  id: ServiceType | "free_scan";
  kind: ServiceKind;
  name: string;
  short: string;
  priceLabel: string;
  cadence?: string;
  features: string[];
  href: string;
  cta: string;
  highlight?: boolean;
}

/**
 * The one report product. `ai_screening` and `similarity_screening` stay in
 * the enum so older orders still render, but they are no longer offered.
 */
export const reportService = "combined_screening" as const;

export const serviceLabels: Record<ServiceType, string> = {
  ai_screening: "AI-Writing Screening",
  similarity_screening: "Similarity Screening",
  combined_screening: "AI & Similarity Report",
  refinement: "Writing Refinement",
};

export const wordRangeLabel = `${screeningWordRange.min.toLocaleString("en-HK")}–${screeningWordRange.max.toLocaleString("en-HK")} words`;

export const refinementRateLabel = `${formatCredits(refinementPricing.perBlock)} per ${refinementPricing.blockChars} characters`;

/** "Minimum HK$30 (3,000 characters)". */
export const refinementMinimumLabel = `Minimum ${formatCredits(refinementPricing.minimum)} (${(
  (refinementPricing.minimum / refinementPricing.perBlock) *
  refinementPricing.blockChars
).toLocaleString("en-HK")} characters)`;

export const services: ServiceDefinition[] = [
  {
    id: "free_scan",
    kind: "free",
    name: "Preliminary Scan",
    short: "Instant writing-pattern analysis generated by this website.",
    priceLabel: "Free",
    cadence: `${freeScan.dailyLimit} scans / day`,
    features: [
      "Instant result",
      "Six writing-pattern signals",
      "Sentence-level highlights",
      "Not a Turnitin result",
    ],
    href: "/scan",
    cta: "Run free scan",
  },
  {
    id: reportService,
    kind: "screening",
    name: serviceLabels[reportService],
    short: "The AI-writing indicator and similarity result a Turnitin screening returns, from one run.",
    priceLabel: formatCredits(screeningPrices[reportService]),
    cadence: `per report · ${wordRangeLabel}`,
    features: [
      "AI-writing indicator",
      "Similarity percentage",
      "Report file where available",
      "Run with repository storage off",
      "Just paste your text",
    ],
    href: "/services/screening",
    cta: "Get report",
    highlight: true,
  },
  {
    id: "refinement",
    kind: "refinement",
    name: "Writing Refinement",
    short: "Human clarity, flow and style refinement of your own writing.",
    priceLabel: `From ${formatCredits(refinementPricing.minimum)}`,
    cadence: refinementRateLabel,
    features: [
      "Clarity, flow and style",
      "Meaning and citations preserved",
      "Your voice retained",
      refinementMinimumLabel,
    ],
    href: "/services/refinement",
    cta: "Refine my writing",
  },
];

export const disclaimers = {
  turnitin:
    "Turnitin is a third-party service. This platform is independently operated and is not affiliated with, endorsed by, or operated by Turnitin.",
  freeScan:
    "This preliminary assessment identifies writing patterns that may contribute to automated detector risk. It does not determine authorship and is not a Turnitin result.",
  screeningResult:
    "This report reflects the result returned during the screening performed for this submission. Automated indicators should be interpreted carefully and are not, on their own, proof of authorship.",
  noGuarantee:
    "We do not guarantee any particular AI-writing or similarity outcome.",
  refinement:
    "Writing Refinement improves the clarity, flow and style of your own writing. It is not a service for disguising AI-generated or third-party work.",
} as const;
