import Link from "next/link";
import { Check, Minus, ArrowRight } from "lucide-react";
import { Container, SectionHeading } from "@/components/ui/section";
import { Reveal } from "@/components/motion/reveal";
import { buttonClasses } from "@/components/ui/button";
import { freeScan } from "@/config/app";
import { cn } from "@/lib/utils";

const free = [
  ["Instant", true],
  [`${freeScan.dailyLimit} per day, free`, true],
  ["Writing-pattern analysis", true],
  ["Paragraph-level indicators", true],
  ["Generated by this website", true],
  ["Turnitin result", false],
] as const;

const paid = [
  ["Human-processed screening workflow", true],
  ["Turnitin AI-writing indicator, where returned", true],
  ["Turnitin similarity result, where returned", true],
  ["Report delivered to your dashboard", true],
  ["Run with repository storage off", true],
  ["Instant", false],
] as const;

function Row({ label, yes }: { label: string; yes: boolean }) {
  return (
    <li className="flex items-center gap-3 py-2.5 text-[14px]">
      {yes ? (
        <Check className="size-4 shrink-0 text-ok" aria-label="Included" />
      ) : (
        <Minus className="size-4 shrink-0 text-fg-subtle" aria-label="Not included" />
      )}
      <span className={cn(yes ? "text-fg" : "text-fg-subtle")}>{label}</span>
    </li>
  );
}

export function Comparison() {
  return (
    <section className="py-24 sm:py-32">
      <Container>
        <SectionHeading
          align="center"
          eyebrow="Two different things"
          title="An estimate, or an actual screening result."
          body="We keep these apart everywhere: on this page, in your results, in your dashboard and on every receipt."
        />
        <div className="relative mt-14 grid gap-5 md:grid-cols-2">
          <Reveal tilt={4} className="glass rounded-2xl p-7 sm:p-8">
            <p className="font-mono text-[11px] uppercase tracking-[0.18em] text-cyan">Free preliminary scan</p>
            <h3 className="mt-3 text-2xl font-semibold tracking-tight">Preliminary risk estimate</h3>
            <p className="mt-2 text-[14px] text-fg-muted">A fast first-pass reading of your writing patterns.</p>
            <ul className="mt-6 divide-y divide-[var(--line)] border-t border-[var(--line)]">
              {free.map(([l, y]) => <Row key={l} label={l} yes={y} />)}
            </ul>
            <Link href="/scan" className={buttonClasses("secondary", "md", "mt-7 w-full")}>
              Run free scan
            </Link>
          </Reveal>
          <Reveal delay={0.1} tilt={4} className="glass-strong relative overflow-hidden rounded-2xl p-7 sm:p-8">
            <div aria-hidden className="absolute -right-24 -top-24 size-64 rounded-full bg-accent/20 blur-3xl" />
            <p className="relative font-mono text-[11px] uppercase tracking-[0.18em] text-accent">Screening service</p>
            <h3 className="relative mt-3 text-2xl font-semibold tracking-tight">Actual screening result</h3>
            <p className="relative mt-2 text-[14px] text-fg-muted">The result returned by a Turnitin screening of your document.</p>
            <ul className="relative mt-6 divide-y divide-[var(--line)] border-t border-[var(--line)]">
              {paid.map(([l, y]) => <Row key={l} label={l} yes={y} />)}
            </ul>
            <Link href="/services/screening" className={buttonClasses("primary", "md", "relative mt-7 w-full")}>
              Request screening
              <ArrowRight className="size-4" />
            </Link>
          </Reveal>
        </div>
      </Container>
    </section>
  );
}
